baseURL = "https://visa.techpawz.com/"
languageCode = "en"
title = "visa"
theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
